### ISSUE TITLE
Long chromosomes are not supported

### ISSUE THREAD

**Issue by SergejN** [ucscGenomeBrowser/kent#38] opened 2020-07-03 22:47 UTC
Dear authors,

I work with the axolotl genome (32Gb in 14 chromosomes, the longest is 3.09Gb). Recently, I wanted to add the GenePred annotation track, but it failed. The generated GenePred file contained wrong coordinates (see example below).

# GTF file
chr7q	ambMex60DD	transcript	1079057453	1079243825	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; gene_name "LOC102367929 [nr]|ZFP2 [hs]"; homolog "XP_025051492.1";
chr7q	ambMex60DD	transcript	1079057453	1079243825	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; gene_name "LOC102367929 [nr]|ZFP2 [hs]"; homolog "XP_025051492.1";
chr7q	ambMex60DD	exon	1079057453	1079060359	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "1";
chr7q	ambMex60DD	exon	1079092841	1079093048	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "2";
chr7q	ambMex60DD	exon	1079123257	1079123388	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "3";
chr7q	ambMex60DD	exon	1079182004	1079182208	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "4";
chr7q	ambMex60DD	exon	1079215424	1079215541	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "5";
chr7q	ambMex60DD	exon	1079243317	1079243825	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1"; exon_number "6";
chr7q	ambMex60DD	CDS	1079059167	1079060359	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1";
chr7q	ambMex60DD	CDS	1079092841	1079093048	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1";
chr7q	ambMex60DD	CDS	1079123257	1079123388	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1";
chr7q	ambMex60DD	CDS	1079182004	1079182208	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1";
chr7q	ambMex60DD	CDS	1079215424	1079215512	1000	-	.	gene_id "AMEX60DD050188"; transcript_id "LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1";

# GenePred file
LOC102367929 [nr]|ZFP2 [hs]|AMEX60DD201050188.1	chr7q	-	1079057452	1079243825	1073741823	1079215512	6	1079057452,1079092840,1079123256,1079182003,1079215423,1079243316,	1079060359,1079093048,1079123388,1079182208,1079215541,1079243825,

The number 1073741823 appears in many entries that fail to be converted and loaded by `hgLoadGenePred`. However, this number is 0x3fffffff, which is defined as a constant BIGNUM throughout the source code.. Therefore, the coordinates are initialized with this value, but for large enough values, the condition ` if (start > line->start)` is never satisfied. That's why this value stays unchanged. Moreover, `int` is not enough to hold the longest coordinates...

````
static void getGroupBoundaries(struct gffGroup *group)
/* Fill in start, end, strand of group from lines. */
{
struct gffLine *line;
long start = 0x3fffffff;
long end = -start;
line = group->lineList;
group->strand = line->strand;
for (; line != NULL; line = line->next)
 {
 if (start > line->start)
 start = line->start;
 if (end < line->end)
 end = line->end;
 }
group->start = start;
group->end = end;
}
```

Is this something that can be fixed easily? I saw that this constant appears at multiple positions in the source code, therefore, it may be a git tricky.
I managed to fix the issue for `hgLoadGenePred` and will submit a pull request. However, although I tried to change as few things as possible, i don't know if the proposed changes may break the code in another tool..

But it would be cool to have a fixed version of the utils especially since our installation of the genome browser supports long chromosomes as such.

thanks a lot!
Sergej

**Comment by braneyboo** [comment] 2020-07-14 19:58
Hey @SergejN ,   Your changes look good, but I'm having a little trouble reproducing it using your input files.   Could you explain exactly what utilities you are using?

**Comment by SergejN** [comment] 2020-07-14 21:04
Hi @braneyboo ,

I see, I pasted the relevant file content and the output, but forgot to add the key piece of information, sorry :)
I use `gtfToGenePred` to convert GTF to GenePred. And that's also the only tool I made changes to. Except for the header files, which are used by multiple tools.

**Comment by braneyboo** [comment] 2020-07-14 21:17
That's what I figured, but I'm not seeing what you describe.  This is probably because something weird is happening with white space in your GTF example.  Can you attach the actual file or provide me a URL?

Sorry to make you jump through hoops, but I want to make sure I can replicate your problem.   Your solution seems perfect.

**Comment by SergejN** [comment] 2020-07-14 21:34
sure, no problem. Here is an example GTF file and the GenePred output file I get from `gtfToGenePred`.
[example.gtf.gz](https://github.com/ucscGenomeBrowser/kent/files/4921630/example.gtf.gz)
[example.gp.zip](https://github.com/ucscGenomeBrowser/kent/files/4921633/example.gp.zip)

**Comment by braneyboo** [comment] 2020-07-14 23:39
I committed your changes as myself.   We haven't started having "outsiders" check things in yet.    Thanks very much for helping us.  

Btw, I also had to change gtfToGenePred.c to account for the longs.

**Closed by braneyboo** 2020-07-14 23:39 UTC
